services:
  - type: web
    name: lms-admin-backend
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: lms-admin-backend
          property: port
      - key: MONGO_URI
        value: mongodb+srv://premarch567:Z6qcWJ8m6iv4ZqRW@cluster0.lyzxobt.mongodb.net/saas-lms-admin?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRE
        value: 30d
